#!/bin/sh

if test -e "$HOME"/.config/rogblue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flatpak Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "4"

echo "# Install Gnome Platform flatpak"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "5"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "6"

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "25"

echo "# Installing Firefox"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Firefox Failed"
        exit 1
fi
echo "30"

echo "# Installing Thunderbird"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.Thunderbird
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Thunderbird Failed"
        exit 1
fi
echo "40"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed"
        exit 1
fi
echo "50"

echo "# Installing OnlyOffice"
/usr/bin/flatpak install --user --noninteractive flathub org.onlyoffice.desktopeditors
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing OnlyOffice Failed"
        exit 1
fi

echo "70"

echo "# Installing Font Downloader"
/usr/bin/flatpak install --user --noninteractive flathub org.gustavoperedo.FontDownloader
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing FontDownloader Failed"
        exit 1
fi
echo "80"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "90"

echo "# Installing Discord"
/usr/bin/flatpak install --user --noninteractive flathub com.discordapp.Discord
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Discord Failed"
        exit 1
fi
echo "90"

echo "# Installing Nextcloud Desktop"
/usr/bin/flatpak install --user --noninteractive flathub com.nextcloud.desktopclient.nextcloud
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Nextcloud Desktop Failed"
        exit 1
fi
echo "90"

echo "# Installing Telegram Desktop"
/usr/bin/flatpak install --user --noninteractive flathub org.telegram.desktop
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Telegram Desktop Failed"
        exit 1
fi
echo "90"

echo "# Installing 1Password"
/usr/bin/flatpak install --user --noninteractive https://downloads.1password.com/linux/flatpak/1Password.flatpakref
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing 1Password Failed"
        exit 1
fi
echo "90"

echo "# Installing BlackBox Terminal "
/usr/bin/flatpak install --user --noninteractive flathub com.raggesilver.BlackBox
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Blackbox Terminal Failed"
        exit 1
fi
echo "95"

echo "# Installing Slack"
/usr/bin/flatpak install --user --noninteractive flathub com.slack.Slack
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Slack Failed"
        exit 1
fi
echo "95"

echo "# Installing Element Desktop"
/usr/bin/flatpak install --user --noninteractive flathub im.riot.Riot
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Element Desktop Failed"
        exit 1
fi
echo "95"

echo "# Installing Whatsapp"
/usr/bin/flatpak install --user --noninteractive flathub io.github.mimbrero.WhatsAppDesktop
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Whatsapp Desktop Failed"
        exit 1
fi
echo "96"

echo "# Installing Filezilla"
/usr/bin/flatpak install --user --noninteractive flathub org.filezillaproject.Filezilla
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Filezilla Failed"
        exit 1
fi
echo "97"

echo "# Installing Filezilla"
/usr/bin/flatpak install --user --noninteractive flathub org.gimp.GIMP
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing GIMP Failed"
        exit 1
fi
echo "97"

echo "# Installing Apple Music client (Cider)"
/usr/bin/flatpak install --user --noninteractive flathub sh.cider.Cider
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Cider Failed"
        exit 1
fi
echo "98"

echo "# Installing Converter"
/usr/bin/flatpak install --user --noninteractive flathub io.gitlab.adhami3310.Converter
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Converter Failed"
        exit 1
fi
echo "99"


echo "# Installing Celluloid Media Player"
/usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Celluloid Failed"
        exit 1
fi
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/rogblue/
touch "$HOME"/.config/rogblue/firstboot-done

) | 
     
   zenity --progress --title="rogBlue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
